// src/users/dto/create-user.dto.ts
import { IsEmail, IsString, IsNotEmpty, IsEnum } from 'class-validator';
import { Country } from '../schemas/user.schema';

/**
 * DTO for creating a new user (HR admin only)
 * Note: Password is automatically generated by the system
 */
export class CreateUserDto {
  @IsEmail()
  @IsNotEmpty()
  email: string;

  @IsString()
  @IsNotEmpty()
  firstName: string;

  @IsString()
  @IsNotEmpty()
  lastName: string;

  @IsString()
  @IsNotEmpty()
  position: string;

  @IsEnum(Country)
  @IsNotEmpty()
  country: Country;
}